# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66f8dda970673acd4674b37afab0e3ad34d36af13e847c61d3aa9be0b76386e085500f24af59773eb3be3e2b5b4d8473892b940dd983d22c2da7986747f8874f

test:
  secret_key_base: bcbe8e991115e515b1927a15d55d4a5b3a4fcd75316700b72a7353611d2b70aad75ef647266a3f374d311ec12cfa6cfbfa7df4b6e5dac8982f1fac026cd16388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
